version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sender:
    build:
      context: ./RabbitMq/RabbitMqSender
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  email_receiver:
    build:
      context: ./RabbitMq/RabbitMqEmailReceiver
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  sms_receiver:
    build:
      context: ./RabbitMq/RabbitMqSmsReceiver
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
