name: Build and Test RabbitMQ Messaging Projects

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build all projects
      run: dotnet build --configuration Release

    - name: Test RabbitMqSender (basic run)
      run: dotnet run --project ./RabbitMqSender

    - name: Test RabbitMqEmailReceiver (basic run)
      run: dotnet run --project ./RabbitMqEmailReceiver

    - name: Test RabbitMqSmsReceiver (basic run)
      run: dotnet run --project ./RabbitMqSmsReceiver
